### ISSUE TITLE
xAPI Logo update

### ISSUE THREAD

**Issue by Brandon-Evans** [Fastlane-LLC/vendor-api-docs#31]
## 🗺️  Requirements
_Where will this work live in the application? What precisely is going to be built/changed?_

We updated the xAPI image however, due to the size of the image and the design, the letters run to the edge of the frame and don't look right.  

![image.png](https://images.zenhubusercontent.com/5ba950b92b32ff642774f905/707ff671-5f32-4fab-9308-26f08d5cb1f8)

#### 😍 Expected Behavior

The image looks sized properly for the frame that it's in. 

## ✔️  Acceptance Criteria
_What are the essential components to mark this work as done?_

- [ ] Use new image with padding added for logo.

Image: 

![xapi-logo](https://user-images.githubusercontent.com/33840965/182412987-d643d576-55fe-4912-9355-acda611f85fe.png)

**Comment by luke-garrison** [comment]
Reviewer: @kentzmann
